import Head from 'next/head'
import { Chat } from 'components/form-chat'
import { CaracteristicasForm } from 'components/form-caracteristicas'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>hola soy el proyecto</div>
      <CaracteristicasForm/>
      {/* <Chat></Chat> */}
      <button onClick={()=>{location.reload()}}>reset</button>
    </>
  )
}
